apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hoplite82-poi-backend-app-dev
  annotations:
    argocd/app-name: hoplite82-poi-backend-app-dev
    backstage.io/kubernetes-id: hoplite82-poi-backend-app
    backstage.io/kubernetes-namespace: hoplite82
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/hoplite82-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/hoplite82/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/hoplite82/deployments/hoplite82-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/hoplite82-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/hoplite82"
  system: workshop-system-hoplite82
  providesApis:
    - backend-api-hoplite82
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-hoplite82
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/hoplite82"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-hoplite82
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://hoplite82-poi-backend-app-hoplite82.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh23-demo/hoplite82-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/hoplite82"
  system: workshop-system-hoplite82
  definition:
    $text: https://github.com/rhdh23-demo/hoplite82-backend/tree/main/src/main/resources/META-INF/openapi.yaml
